app/mailing/forms.py
from flask_wtf import FlaskForm
from wtforms import (
    RadioField, SelectMultipleField,
    BooleanField, 
    SubmitField, 
    )

from .department import Department

class MailingForm(FlaskForm):
    categories_customer = SelectMultipleField("Catégories Tiers")
    categories_contact = SelectMultipleField("Catégories Contact")
    operator_customer = RadioField("Filtre Tiers", choices=[("and", "ET"), ("or", "OU")], default='and')
    operator_contact = RadioField("Filtre Contact", choices=[("and", "ET"), ("or", "OU")], default='and')
    departments_customer = SelectMultipleField("Departements Tiers", choices=Department.tuple("#n (#i)"))
    departments_contact = SelectMultipleField("Departements Contacts", choices=Department.tuple("#n (#i)"))
    add_customer_contacts = BooleanField("Ajouter les contacts des tiers ?")
    submit = SubmitField("Ajouter")
    delete = SubmitField("Vider")

app/mailing/__init__.py
from flask import Blueprint

bp = Blueprint('mailing', __name__)

from app.mailing import routes

app/mailing/routes.py
from datetime import datetime

from flask import redirect, render_template, request, send_from_directory, session, url_for, current_app
from flask_login import current_user, login_user, logout_user, login_required
from werkzeug.urls import url_parse

from app.mailing import bp
from app import db
from .forms import MailingForm
from app.models import User

from .dolibarr import Dolibarr
from .export import Export




@bp.route('/', methods=["GET", "POST"])
@login_required
def index():
    form = MailingForm()
    if "mailing_emails" in session:  # List of precedent emails selection
        # A list of lists with all the precedent append: [ ['callA@gmail.com', 'callA@gmail.com'], ['callB@gmail.com', 'callB@gmail.com'] ]
        emails = session["mailing_emails"]
    else:
        emails = []

    form.categories_contact.choices = Dolibarr.categories(types=["contact"])
    form.categories_customer.choices = Dolibarr.categories(types=["customer"])

    if form.validate_on_submit():
        if form.submit.data:  # Submit button
            extracted_emails = []  # A local list of all emails from selected categories, added to session emails at the end
            emails_contact = Dolibarr.get(filters={
                "type": ["contact"],
                "categories": form.categories_contact.data,
                "departments": form.departments_contact.data,
                "operator": form.operator_contact.data
            })
            emails_contact = emails_contact.values()
            emails_customer = Dolibarr.get(filters={
                "type": ["customer"], 
                "contacts": form.add_customer_contacts.data,
                "categories": form.categories_customer.data,
                "departments": form.departments_customer.data,
                "operator": form.operator_customer.data
                })
            emails_customer = emails_customer.values()  # Get return a dict, we only want emails. 
            #emails_customer = Dolibarr.emails(["customer"], form.categories_customer.data, form.operator_customer.data)
            extracted_emails.extend(emails_contact)
            extracted_emails.extend(emails_customer)

            emails.append(extracted_emails)
        else:  # Delete button -> Empty emails list
            emails = []

    form.categories_contact.data = ""  # Empty default value at each reload 
    form.categories_customer.data = ""

    emails = Dolibarr.delete_duplicates(emails)
    session["mailing_emails"] = emails  # Update session var
    return render_template('mailing/index.html', form=form, emails=emails)


@bp.route('/export/')
@login_required
def export():
    if "mailing_emails" in session:  # List of precedent emails selection
        emails = session["mailing_emails"]
    
        # Extract emails
        full_emails = []  # A single list of all the emails
        for sublist in emails:
            for email in sublist:
                if email not in full_emails:
                    full_emails.append(email)

        # Generate path
        export_dir = current_app.config["EXPORT_FOLDER"]
        ts = datetime.timestamp(datetime.now())
        ts = str(ts).split('.')[0]  # Remove miliseconds from timestamp
        username = current_user.username
        filename = f'mailing-{username}-{ts}.csv'
        path = Export.path([current_app.root_path, export_dir, filename])

        # Generate file
        Export.csv(full_emails, path)
        return send_from_directory(directory=export_dir, path=filename, as_attachment=True)

app/templates/mailing/index.html
{% extends "base.html" %}

{% block title %}Mailing - Dolimore{% endblock %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/multiselect.css') }}">
<script src="{{ url_for('static', filename='js/multiselect.min.js') }}"></script>
<div class="container mt-3">
<div class="row mb-3">
    <div class="col">
        <h1>Générateur de mailing</h1>
    </div>
</div>

<form action="" method="post">
    {{ form.hidden_tag() }}

    <div class="form-group row">
        <div class="col form-control">
            <h2>Tiers</h2>
            <div class="d-flex align-bottom">
                <div class="d-inline-block">
                    <h4 class="text-muted">Catégories</h4>   
                </div>
                {% for operator in form.operator_customer %}
                    <div class="d-inline-block pt-1 form-check form-check-inline">
                    {{ operator() }} {{ operator.label }}
                    </div>
                {% endfor %}
            </div>
            {{ form.categories_customer(class="form-control") }}

            <div class="my-2">
                <h4 class="text-muted">Départements</h4>
                {{ form.departments_customer(class="form-control") }}
            </div>

            <div class="form-check">
                {{ form.add_customer_contacts() }} {{ form.add_customer_contacts.label }}
            </div>
        </div>

        <div class="col form-control">
            <h2>Contact</h2>
            <div class="d-flex align-bottom">
                <div class="d-inline-block">
                    <h4 class="text-muted">Catégories</h4>   
                </div>
                {% for operator in form.operator_contact %}
                    <div class="d-inline-block pt-1 form-check form-check-inline">
                    {{ operator }} {{ operator.label }}
                    </div>
                {% endfor %}

            </div>

            {{ form.categories_contact(class="form-control") }}

        </div>
    </div>
    <div class="pt-3 text-center row">
        <div class="col">
            {{ form.submit(class="btn btn-primary") }}
            <button type="button" class="btn btn-success" onclick="location.href='{{ url_for('mailing.export') }}'">Télécharger</button>
            {{ form.delete(class="btn btn-outline-danger") }}
        </div>
    </div>
</form>
    <ul>
        {% for sublist in emails %}
            <li>Ajout {{ loop.index }}:</li>
            <ul>
            {% for email in sublist %}
                <li>{{ email }}</li>
            {% endfor %}
            </ul>
        {% endfor %}
    </ul>
</div>
</div>
<script>
    document.multiselect('#categories_customer');
    document.multiselect('#departments_customer');
    document.multiselect('#categories_contact');
</script>
{% endblock %}