app/mailing/forms.py
from flask_wtf import FlaskForm
from wtforms import (
    RadioField, SelectMultipleField,
    BooleanField, 
    SubmitField, 
    )

from .department import Department

class MailingForm(FlaskForm):
    categories_customer = SelectMultipleField("Catégories Tiers")
    categories_contact = SelectMultipleField("Catégories Contact")
    operator_customer = RadioField("Filtre Tiers", choices=[("and", "ET"), ("or", "OU")], default='and')
    operator_contact = RadioField("Filtre Contact", choices=[("and", "ET"), ("or", "OU")], default='and')
    departments_customer = SelectMultipleField("Departements Tiers", choices=Department.tuple("#n (#i)"))
    departments_contact = SelectMultipleField("Departements Contacts", choices=Department.tuple("#n (#i)"))
    add_customer_contacts = BooleanField("Ajouter les contacts des tiers ?")
    submit = SubmitField("Ajouter")
    delete = SubmitField("Vider")

app/contract/__init__.py
from flask import Blueprint

bp = Blueprint('contract', __name__)

from app.contract import routes

app/mailing/__init__.py
from flask import Blueprint

bp = Blueprint('mailing', __name__)

from app.mailing import routes

app/mailing/routes.py
from datetime import datetime

from flask import redirect, render_template, request, send_from_directory, session, url_for, current_app
from flask_login import current_user, login_user, logout_user, login_required
from werkzeug.urls import url_parse

from app.mailing import bp
from app import db
from .forms import MailingForm
from app.models import User

from .dolibarr import Dolibarr
from .export import Export




@bp.route('/', methods=["GET", "POST"])
@login_required
def index():
    form = MailingForm()
    if "mailing_emails" in session:  # List of precedent emails selection
        # A list of lists with all the precedent append: [ ['callA@gmail.com', 'callA@gmail.com'], ['callB@gmail.com', 'callB@gmail.com'] ]
        emails = session["mailing_emails"]
    else:
        emails = []

    form.categories_contact.choices = Dolibarr.categories(types=["contact"])
    form.categories_customer.choices = Dolibarr.categories(types=["customer"])

    if form.validate_on_submit():
        if form.submit.data:  # Submit button
            extracted_emails = []  # A local list of all emails from selected categories, added to session emails at the end
            emails_contact = Dolibarr.get(filters={
                "type": ["contact"],
                "categories": form.categories_contact.data,
                "departments": form.departments_contact.data,
                "operator": form.operator_contact.data
            })
            emails_contact = emails_contact.values()
            emails_customer = Dolibarr.get(filters={
                "type": ["customer"], 
                "contacts": form.add_customer_contacts.data,
                "categories": form.categories_customer.data,
                "departments": form.departments_customer.data,
                "operator": form.operator_customer.data
                })
            emails_customer = emails_customer.values()  # Get return a dict, we only want emails. 
            #emails_customer = Dolibarr.emails(["customer"], form.categories_customer.data, form.operator_customer.data)
            extracted_emails.extend(emails_contact)
            extracted_emails.extend(emails_customer)

            emails.append(extracted_emails)
        else:  # Delete button -> Empty emails list
            emails = []

    form.categories_contact.data = ""  # Empty default value at each reload 
    form.categories_customer.data = ""

    emails = Dolibarr.delete_duplicates(emails)
    session["mailing_emails"] = emails  # Update session var
    return render_template('mailing/index.html', form=form, emails=emails)


@bp.route('/export/')
@login_required
def export():
    if "mailing_emails" in session:  # List of precedent emails selection
        emails = session["mailing_emails"]
    
        # Extract emails
        full_emails = []  # A single list of all the emails
        for sublist in emails:
            for email in sublist:
                if email not in full_emails:
                    full_emails.append(email)

        # Generate path
        export_dir = current_app.config["EXPORT_FOLDER"]
        ts = datetime.timestamp(datetime.now())
        ts = str(ts).split('.')[0]  # Remove miliseconds from timestamp
        username = current_user.username
        filename = f'mailing-{username}-{ts}.csv'
        path = Export.path([current_app.root_path, export_dir, filename])

        # Generate file
        Export.csv(full_emails, path)
        return send_from_directory(directory=export_dir, path=filename, as_attachment=True)

app/routes.py
from flask import redirect, render_template, request, session, url_for, Blueprint
from flask_login import current_user, login_user, logout_user, login_required
from werkzeug.urls import url_parse

from app import db
from app.forms import LoginForm, SignupForm
from app.models import User


bp = Blueprint('main', __name__, url_prefix="")


@bp.route('/')
@bp.route('/index/')
def index():
    return render_template('index.html')


@bp.route('/login', methods=['GET', 'POST'])
def login():
    errors = []
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = LoginForm()
    if form.validate_on_submit():  # POST processing
        user = User.query.filter_by(email=form.email.data).first()
        if user is None:
            errors.append("Pas d'utilisateurs avec cet email")
        elif not user.check_password(form.password.data):
            errors.append("Mot de passe incorrect")
        else:
            login_user(user, remember=form.remember_me.data)
            next_page = request.args.get('next')
            if not next_page or url_parse(next_page).netloc != '':  # Check if there is a next_page and if the next_page is a relative path
                next_page = url_for('main.index')
            return redirect(next_page)
    return render_template('login.html', form=form, errors=errors)


@bp.route('/logout/')
def logout():
    logout_user()
    return redirect(url_for('main.index'))

@bp.before_app_request
def firstconnection():
    if len(User.query.all()) == 0:  # No user in db
        form = SignupForm()
        errors = []

        if form.validate_on_submit():
            username = form.username.data
            email = form.email.data
            password = form.password.data
            u = User(username=username, email=email, is_admin=True)
            u.set_password(password)
            db.session.add(u)
            db.session.commit()
            return redirect(url_for('main.login'))
        
        if request.method == 'POST' and not form.validate():
            errors.append(form.errors)

        return render_template('firstconnection.html', form=form, errors=errors)
    

app/templates/base.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}Dolimore{% endblock %}
    </title>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
</head>

<body>
    <header class="flex-column">

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark flex-md-row py-2 px-3">
            <a class="navbar-brand" href="#">
                <img src="{{ url_for('static', filename='img/logo.webp') }}" height="50" class="d-inline-block" alt="">
                Dolimore
            </a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="#navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="navbar collapse navbar-collapse" id="navbarCollapse">
              <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.index') }}">Accueil</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('mailing.index') }}">Mailing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('contract.index') }}">Contrat</a>
                </li>
              </ul>
                <ul class="navbar-nav justify-content-end">
                    {% if current_user.is_anonymous %}
                    <li class="nav-item">
                        <button class="btn btn-outline-success btn-sm" onclick="location.href='{{ url_for('main.login') }}'">Connexion</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <span class="nav-link disabled">{{ current_user.email }}</span>
                    </li>
                    <li class="nav-item">
                        <button class="btn btn-outline-secondary btn-sm" onclick="location.href='{{ url_for('main.logout') }}'">Deconnexion</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    
    </header>
<div class="container">
    {% block content %}
    <p>Hello World</p>
    {% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

app/templates/firstconnection.html
{% extends 'base.html' %}


{% block title %}Premiers pas - Dolimore{% endblock %}


{% block content %}
<div class="container-fluid mt-5 ">
    <div class="col text-center">
        <h1>Ajouter un administrateur</h1>
    </div>

    <form action="" method="post" class="form-signin">
        {{ form.hidden_tag() }}

        {% if errors %}
        <div class="form-group alert alert-danger">
            <ul>
                {% for error in errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}

        {{ form.username.label(class="visually-hidden") }}
        {{ form.username(size=64, class="form-control", placeholder="Nom de l'admin", autofocus='') }}

        {{ form.email.label(class="visually-hidden") }}
        {{ form.email(size=64, class="form-control", placeholder="Adresse email", autofocus='') }}

        {{ form.password.label(class="visually-hidden") }}
        {{ form.password(size=64, class="form-control", placeholder="Mot de passe") }}

        {{ form.password_confirmation.label(class="visually-hidden") }}
        {{ form.password_confirmation(size=64, class="form-control", placeholder="Répeter le mot de passe") }}


        <div class="d-grid">
            {{ form.submit(class="btn btn-lg btn-primary") }}
        </div>
    </form>
</div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block title %}Accueil - Dolimore{% endblock %}

{% block content %}
<div class="container-fluid mt-3 text-center">
    <div class="row">
        <div class="col">
            <h1 class="mb-4">DOLIMORE</h1>
            {% if current_user.is_anonymous %}
            <div class="d-grid">
                <button type="button" class="btn btn-lg btn-success" onclick="location.href='{{ url_for('main.login') }}'">Se connecter</button>
            </div>
            {% else %}
            <div class="text-center h3 text-muted">
                Bonjour {{ current_user.username }}
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block title %}Connexion - Dolimore{% endblock %}

{% block content %}
<div class="container-fluid mt-5 ">
    <div class="col text-center">
        <h1>Se Connecter</h1>
    </div>

    <form action="" method="post" class="form-signin">
        {{ form.hidden_tag() }}

        {% if errors %}
        <div class="form-group alert alert-danger">
            <ul>
                {% for error in errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}

        {{ form.email.label(class="visually-hidden") }}
        {{ form.email(size=64, class="form-control", placeholder="Adresse mail", autofocus='') }}

        {{ form.password.label(class="visually-hidden") }}
        {{ form.password(size=64, class="form-control", placeholder="Mot de passe") }}

        <div class="form-group my-3">
            {{ form.remember_me() }} {{ form.remember_me.label }}
        </div>

        <div class="d-grid">
            {{ form.submit(class="btn btn-lg btn-primary") }}
        </div>
    </form>
</div>
{% endblock %}

app/templates/mailing.html
{% extends "base.html" %}

{% block title %}Mailing - Dolimore{% endblock %}

{% block content %}
<div class="container mt-3">
<div class="row mb-3">
    <div class="col">
        <h1>Générateur de mailing</h1>
    </div>
</div>

<form action="" method="post">
    {{ form.hidden_tag() }}

    <div class="form-group row">
        <div class="col form-control">
            <div class="d-flex align-bottom">
                <div class="d-inline-block"><h2>Tiers</h2></div>

                {% for operator in form.operator_customer %}
                <div class="d-inline-block pt-3 form-check form-check-inline">
                {{ operator() }} {{ operator.label }}
                </div>
                {% endfor %}

            </div>

            {{ form.categories_customer(class="form-control") }}

            <div class="form-check">
                {{ form.add_customer_contacts() }} {{ form.add_customer_contacts.label }}
            </div>
        </div>

        <div class="col form-control">
            <div class="d-flex align-bottom">
                <div class="d-inline-block"><h2>Contact</h2></div>
            
                {% for operator in form.operator_contact %}
                <div class="d-inline-block pt-3 form-check form-check-inline">
                {{ operator }} {{ operator.label }}
                </div>
                {% endfor %}

            </div>

            {{ form.categories_contact(class="form-control") }}
        </div>
    </div>
    <div class="pt-3 text-center row">
        <div class="col">
            {{ form.submit(class="btn btn-primary") }}
            <button type="button" class="btn btn-success" onclick="location.href='{{ url_for('main.mailing_export') }}'">Télécharger</button>
            {{ form.delete(class="btn btn-outline-danger") }}
        </div>
    </div>
</form>
    <ul>
        {% for sublist in emails %}
            <li>Ajout {{ loop.index }}:</li>
            <ul>
            {% for email in sublist %}
                <li>{{ email }}</li>
            {% endfor %}
            </ul>
        {% endfor %}
    </ul>
</div>
</div>
{% endblock %}